version: '3.8'

x-environment: &airflow_environment
  - AIRFLOW__CORE__EXECUTOR=LocalExecutor
  - AIRFLOW__CORE__LOAD_DEFAULT_CONNECTIONS=False
  - AIRFLOW__CORE__LOAD_EXAMPLES=False
  - AIRFLOW__CORE__SQL_ALCHEMY_CONN=postgresql://admin:admin@postgres:5432/airflow
  - AIRFLOW__CORE__STORE_DAG_CODE=True
  - AIRFLOW__CORE__STORE_SERIALIZED_DAGS=True
  - AIRFLOW__WEBSERVER__EXPOSE_CONFIG=True
  - AIRFLOW__WEBSERVER__RBAC=False

x-airflow-image: &extended_airflow extended_airflow

services:
  scraper:
    build: .
    container_name: scraper
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgresql://scraperadmin:subodh9818@db:5432/scraperdb
    volumes:
      - .:/app

  db:
    image: postgres:15
    container_name: db
    restart: always
    environment:
      POSTGRES_DB: scraperdb
      POSTGRES_USER: scraperadmin
      POSTGRES_PASSWORD: subodh9818
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  airflow:
    image: apache/airflow:2.8.1-python3.11
    container_name: airflow
    restart: always
    depends_on:
      - db
    environment:
      - AIRFLOW__CORE__EXECUTOR=LocalExecutor
      - AIRFLOW__CORE__SQL_ALCHEMY_CONN=postgresql+psycopg2://scraperadmin:subodh9818@db:5432/scraperdb
      - AIRFLOW__CORE__LOAD_EXAMPLES=False
    volumes:
      - ./dags:/opt/airflow/dags
      - ./logs:/opt/airflow/logs
      - ./plugins:/opt/airflow/plugins
    ports:
      - "8080:8080"
    command: >
      bash -c "
      pip install psycopg2-binary &&
      while ! pg_isready -h db -p 5432 -U scraperadmin; do sleep 1; done &&
      airflow db migrate &&
      airflow users create --username admin \
        --firstname subodh \
        --lastname dhungel \
        --role Admin \
        --email subodhdhungel20@gmail.com \
        --password subodh9818 &&
      exec airflow webserver
      "

  airflow-scheduler:
    image: apache/airflow:2.8.1-python3.11
    container_name: airflow-scheduler
    restart: always
    depends_on:
      - db
    environment:
      - AIRFLOW__CORE__EXECUTOR=LocalExecutor
      - AIRFLOW__CORE__SQL_ALCHEMY_CONN=postgresql+psycopg2://scraperadmin:subodh9818@db:5432/scraperdb
      - AIRFLOW__CORE__LOAD_EXAMPLES=False
    volumes:
      - ./dags:/opt/airflow/dags
      - ./logs:/opt/airflow/logs
      - ./plugins:/opt/airflow/plugins
    command: >
      bash -c "
      pip install psycopg2-binary &&
      while ! pg_isready -h db -p 5432 -U scraperadmin; do sleep 1; done &&
      exec airflow scheduler
      "

volumes:
  pgdata:
